# this file defines the inputs, outputs and main entrypoint for your action
name : 'Hello World'
description: 'Greeting someone and show timestamp'
inputs: 
  who-to-greet: # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of input
    description: 'The time we greeted you'
runs: 
  using: 'node12'
  main: 'index.js'