name: issues test for slack

on:
  issues:
    types: [opened, deleted, closed]
      

jobs:
  open-issue:
    runs-on: ubuntu-latest
    steps:
      - name: action step
        env:
          REPO: ${{ github.event.repository.name }}
          OWNER: ${{ github.event.repository.owner.login }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' ${{ secrets.SLACK_WEBHOOK }}
