name: Create index.file sample

on:
  issues:
    types:
      - opened
      

jobs:
  open-issue:
    runs-on: ubuntu-latest
    steps:
      - name: action step
        env:
          REPO: ${{ github.event.repository.name }}
          OWNER: ${{ github.event.repository.owner.login }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          curl -s -X POST https://api.github.com/repos/$OWNER/$REPO/issues/$ISSUE_NUMBER/comments \
          -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
          -d '{ "body" : "Hi there ${{ github.event.issue.user.login }}, we will check this issue."}'